dist: xenial

language: python
python: '3.7'

# branches:
#   only:
#     - master

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install

test:
  - pytest

build:
  - poetry build

publish:
  - provider: build
    skip_cleanup: true
    script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
    on:
      branch: master
