dist: xenial

language: python
python: '3.7'

# branches:
#   only:
#     - master

stages:
  - install
  - test
  - deploy

jobs:
  include:
    - stage: install
      script:
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
    - stage: test
      script:
        pytest
    - stage: publish
      script: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
      on:
        branch: master
